Autoformat all files

diff --git a/pm/power.d/samsung-tools_vm-writeback-time b/pm/power.d/samsung-tools_vm-writeback-time
--- a/pm/power.d/samsung-tools_vm-writeback-time
+++ b/pm/power.d/samsung-tools_vm-writeback-time
@@ -9,7 +9,7 @@ cat <<EOF
 --------
 $0: VM writeback time parameters.
 
-This hook has 1 tuneable parameter. 
+This hook has 1 tuneable parameter.
 VM_WRITEBACK_TIME_POWERSAVE = controls whether we will try to save power on battery.
 Defaults to true.
 
@@ -17,16 +17,16 @@ EOF
 }
 
 vm_writeback_time_powersave() {
-    [ "$VM_WRITEBACK_TIME_POWERSAVE" = "true" ] || exit $NA
-    printf "Setting VM writeback time to %d..." "$1"
-    echo $1 > "/proc/sys/vm/dirty_writeback_centisecs" && echo Done. || echo Failed.
+	[ "$VM_WRITEBACK_TIME_POWERSAVE" = "true" ] || exit $NA
+	printf "Setting VM writeback time to %d..." "$1"
+	echo $1 > "/proc/sys/vm/dirty_writeback_centisecs" && echo Done. || echo Failed.
 }
 
 case $1 in
-    true) vm_writeback_time_powersave 1500 ;;
-    false) vm_writeback_time_powersave 500 ;;
-    help) help;;
-    *) exit $NA
+	true) vm_writeback_time_powersave 1500 ;;
+	false) vm_writeback_time_powersave 500 ;;
+	help) help;;
+	*) exit $NA
 esac
 
 exit 0
